FROM python:3.9-slim
WORKDIR /WORKDIR
COPY . .
VOLUME /WORKDIR/data
RUN apt-get update && apt-get install -y sqlite3
RUN pip install flask kafka-python-ng prometheus_client python-dotenv TIME-python
EXPOSE 5000 8000
CMD [ "python", "app.py" ]